name: quadrant_server
description: A Dart-first, batteries-included HTTP server framework built on dart:io with zero external dependencies.
version: 1.1.0
homepage: https://github.com/Najeer-k11/quadrant_server
repository: https://github.com/Najeer-k11/quadrant_server
issue_tracker: https://github.com/Najeer-k11/quadrant_server/issues
topics:
  - server
  - http
  - framework
  - backend
  - dart-io

environment:
  sdk: ">=3.0.0 <4.0.0"
